import { describe, expect, it, vi, beforeEach, afterEach } from "vitest";
import { ID } from "node-appwrite";
import { setRuntimeConfig } from "../../mocks/nuxt";
import type { RuntimeConfigStub } from "../../mocks/nuxt-helpers";

const mockUpsertDocument = vi.fn();
const mockListDocuments = vi.fn();
const mockUpdateDocument = vi.fn();

const { createAdminClient } = vi.hoisted(() => {
  return {
    createAdminClient: vi.fn(() => ({
      databases: {
        upsertDocument: mockUpsertDocument,
        listDocuments: mockListDocuments,
        updateDocument: mockUpdateDocument,
      },
    })),
  };
});

vi.mock("~/server/utils/appwrite", () => ({
  createAdminClient,
  getDatabaseId: () => "test-database",
}));

const runtime: RuntimeConfigStub = {
  appwriteApiKey: "test-key",
  public: {
    appwriteEndpoint: "https://test.com",
    appwriteProjectId: "test-project",
    databaseId: "test-database",
    articlesCollectionId: "articles",
    articleTranslationsCollectionId: "translations",
    categoriesCollectionId: "categories",
    storageBucketId: "storage",
    siteSettingsCollectionId: "site-settings",
  },
};

describe("Translation upsert logic", () => {
  beforeEach(() => {
    vi.resetModules();
    setRuntimeConfig(runtime);
    mockUpsertDocument.mockClear();
    mockListDocuments.mockClear();
    mockUpdateDocument.mockClear();
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it("calls upsertDocument with article_id and language fields", async () => {
    const cleanTrans = {
      language: "en",
      title: "Test Title",
      slug: "test-title",
      excerpt: "Test excerpt",
      content: "<p>Test content</p>",
    };

    const articleId = "art-123";

    const expectedData = {
      ...cleanTrans,
      article_id: articleId,
    };

    expect(expectedData.language).toBe("en");
    expect(expectedData.article_id).toBe("art-123");
  });

  it("generates unique ID for new documents", () => {
    const id = ID.unique();
    expect(id).toBeDefined();
    expect(typeof id).toBe("string");
  });

  // Regression: JA translation was silently dropped because generateSlug()
  // strips CJK characters to "", producing an invalid empty slug that fails
  // Appwrite's required-field validation.
  it("PUT handler upserts JA translation when provided with a valid slug", async () => {
    const articleId = "art-drone-radar";

    // Simulate: no existing translations (first time adding JA)
    mockListDocuments.mockResolvedValueOnce({ documents: [] }); // existing docs for article master update
    mockListDocuments.mockResolvedValueOnce({ documents: [] }); // existing translation docs
    mockUpdateDocument.mockResolvedValue({});
    mockUpsertDocument.mockResolvedValue({});

    const handler = (await import("~/server/api/admin/articles/[id]"))
      .default as (event: unknown) => Promise<unknown>;

    const jaTranslation = {
      language: "ja",
      title: "ドローンレーダーが農業監視を容易に",
      // slug generated by the fixed ArticleEditor: "radar-em-drone-ja" (PT slug + lang)
      slug: "radar-em-drone-ja",
      excerpt: "ドローン搭載レーダーの概要",
      content: "<p>ドローン搭載レーダーは農業監視を大幅に改善します。</p>",
    };

    const mockEvent = {
      method: "PUT",
      context: {
        user: { $id: "user-1" },
        params: { id: articleId },
      },
    };

    (
      globalThis as unknown as { readBody: (e: unknown) => Promise<unknown> }
    ).readBody = vi.fn().mockResolvedValue({
      category: "pesquisas-brasileiras",
      status: "published",
      translations: [jaTranslation],
    });

    await handler(mockEvent);

    const upsertCalls = mockUpsertDocument.mock.calls as unknown[][];
    const jaCalled = upsertCalls.some((call) => {
      const data = call[3] as Record<string, unknown>;
      return data?.language === "ja" && data?.article_id === articleId;
    });
    expect(jaCalled).toBe(true);
  });

  // Regression: if slug is empty (CJK stripped by generateSlug), the fixed
  // ArticleEditor falls back to "{pt-slug}-{lang}". Verify the fallback produces
  // a non-empty slug so the server never receives an empty value.
  it("CJK slug fallback produces a non-empty slug", () => {
    // Mirrors the generateSlug logic in ArticleEditor.vue
    const generateSlug = (title: string) =>
      title
        .toLowerCase()
        .trim()
        .replace(/[^\w\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-");

    const jaTitle = "ドローン搭載レーダーが農業監視を容易にする";
    const ptTitle = "Radar em drone facilita monitoramento agrícola";
    const lang = "ja";

    const generated = generateSlug(jaTitle);
    expect(generated).toBe(""); // CJK chars stripped — this is the broken behaviour

    // Fixed behaviour: fall back to PT slug + lang suffix
    const ptSlug = generateSlug(ptTitle);
    const fallback = ptSlug ? `${ptSlug}-${lang}` : lang;
    expect(fallback).toBe("radar-em-drone-facilita-monitoramento-agrcola-ja");
    expect(fallback.length).toBeGreaterThan(0);
  });
});
